services:
  - type: web
    name: pnw-tree-id
    runtime: docker
    plan: free
    envVars:
      - key: MODEL_CHECKPOINT
        value: checkpoints/best_model.pt
      - key: CHECKPOINT_URL
        value: https://github.com/vsriram24/pnw-tree-id/releases/download/v1.0/best_model.pt
